#!/usr/bin/env ruby
require "doxieland"
require "thor"
require "ruby-progressbar"
require 'hirb'
require 'pry'
class CLI < Thor
  include Thor::Actions

  class_option 'scanner-ip', desc:'your scanners network address', banner: 'xxx.xxx.xxx.xxx', type: :string, aliases: '-i'
  class_option :password, desc:'your scanners password', type: :string, aliases: '-p'

  def initialize(*args, **kargs)
    super

    @config = (options || HashWithIndifferentAccess.new).reverse_merge(Doxieland.config)
    @client = Doxieland::Client.new(@config)
  end

  desc "info", "show information about your scanner"
  def info
    response =
      @client.api do |api|
        api.get_info.result
      end

      puts Hirb::Helpers::AutoTable.render(
          response,
          description:  false,
          headers:      false
        )
  end

  desc "list", "list all scans saved in your scanners memory"
  def list
    scans = @client.api { |api| api.list_scans.result }

    if scans.none?
      log.info "no scans found"
      exit
    end

    puts Hirb::Helpers::AutoTable.render(
      scans,
      fields: [:name, :path],
      description: false
    )

    log.info "#{scans.length} scans available"
  end

  desc "download", <<-EOT.strip_heredoc
    download all scans from your scanner to your computer

    Available placeholders for filename format strings:
      %{number} - the image number
      %{date} - the current date as DD.MM.YYYY
      %{time} - the current time as HH:MM:SS

    You can further format date and time by passing format options inside the placeholders, separated by a colon:

      %{date:%Y-%m-%d}

    See http://ruby-doc.org/core-2.2.0/Time.html#method-i-strftime for all available date and time formatting options.

  EOT
  method_option :to, desc: "the directory to save the scans to. Defaults to .", type: :string, aliases: '-t'
  method_option :filenames,
                type: :string,
                aliases: '-f',
                banner: '"FORMAT_STRING"',
                desc: 'filename format string. Default: "doxie_scan_%{date}-%{number}"'
  method_option :pdf, desc: "convert scans to PDF. Requires ImageMagick to be installed", type: :boolean
  method_option :delete, desc: "delete scans from scanner after download", type: :boolean, aliases: '-d'
  def download
    if @config[:pdf]
      unless command_available?('convert')
        log.fatal "could not find the 'convert' command. PDF conversion requires ImageMagick to be installed"
        exit(false)
      end
    end

    @client.create_save_path

    Doxieland::Scan.save_path   = @client.save_path
    Doxieland::Scan.name_format = @config[:filenames] if @config[:filenames]

    scans = @client.api do |api|
      api.list_scans.result
    end

    if scans.none?
      log.info "0 scans available for download on scanner"
      exit
    end

    log.info "downloading #{scans.length} scans to " + Rainbow(@client.save_path).cyan.bright

    progressbar = create_progressbar(starting_at: 0, total: scans.length)

    deletable_paths = []
    save_count      = 0

    scans.each do |remote_scan|
      progressbar.title = "downloading #{remote_scan[:name]}".truncate(22).ljust(25)

      scan = @client.api { |api| api.get_scan(path: remote_scan[:path]).result }

      if @config[:pdf]
        scan.file_type = 'pdf'
        progressbar.title = "saving #{remote_scan[:name]} as PDF".truncate(22).ljust(25)
      else
        progressbar.title = "saving #{remote_scan[:name]}".truncate(22).ljust(25)
      end

      if scan.save
        save_count += 1
        deletable_paths << remote_scan[:delete_path]
      else
        log.progress_warn "skipped existing file #{scan.path}", progressbar
      end

      progressbar.increment
    end

    if options[:delete] && deletable_paths.any?
      progressbar = create_progressbar(title: "deleting scans".ljust(20))

      @client.api { |api| api.delete_scans(paths: deletable_paths).result }

      progressbar.progress = 1
      progressbar.total    = 1
      progressbar.finish
    end

    log.success "#{save_count} scans downloaded"
  end

  desc "defaults", "show or set default options for doxieland"
  method_option :to, desc: "the directory to save the scans to. Defaults to .", type: :string, aliases: '-t'
  method_option :filenames,
                type: :string,
                aliases: '-f',
                banner: '"FORMAT_STRING"'
  method_option :pdf, desc: "convert scans to PDF. Requires ImageMagick to be installed", type: :boolean
  method_option :delete, desc: "delete scans from scanner after download", type: :boolean, aliases: '-d'
  def defaults
    if options.none?
      config = Doxieland.config

      if config.any?
        puts Hirb::Helpers::AutoTable.render(
          config,
          description:  false,
          headers:      { 0 => 'option', 1 => 'value' }
        )
      else
        log.info "no defaults set"
      end

    else
      File.open(Doxieland.config_path, 'w') { |file| file << YAML.dump(options) }

      puts Hirb::Helpers::AutoTable.render(
        config,
        description:  false,
        headers:      { 0 => 'option', 1 => 'value' }
      )

      log.success "new default settings saved"
    end
  end

  desc "console", "starts a Pry REPL session", hide: true
  def console
    begin
      require 'pry'
    rescue LoadError
      log.fatal "doxieland console requires Pry to be installed: gem install pry"
      exit
    end
    binding.pry
  end

  no_commands do
    def log
      @client.log
    end

    def create_progressbar(**kargs)
      kargs.reverse_merge!({
        total: nil,
        format: "%t (%c of %C) |%b\u{1F431}%i| %E",
        progress_mark: "\u{2728}",
        remainder_mark: " ", title: ' ' * 25
      })
      ProgressBar.create(**kargs)
    end

    def command_available?(command)
      `which #{command}`.present? && $?.exitstatus == 0
    end
  end
end

CLI.start( ARGV.any? ? ARGV : ['help'] )